export enum GarmentType {
  PANTS = 'Broek',
  JEANS = 'Jeans',
  SHORTS = 'Short',
  JUMPSUIT = 'Jumpsuit',
  DRESS = 'Jurk',
  SKIRT = 'Skirt',
  LONGSLEEVE = 'Longsleeve',
  TSHIRT = 'T-shirt',
  TOP = 'Top',
  POLO = 'Polo',
  HOODIE = 'Hoodie',
  SWEATER = 'Sweater',
  CARDIGAN = 'Cardigan',
  KNITWEAR = 'Knitwear',
  BLAZER = 'Blazer',
  JACKET = 'Jacket',
  COAT = 'Coat',
}
